package com.jueqiao.jianghu.nav

/**
 * Route constants for Navigation Compose.
 * Mirrors the React Native expo-router route names.
 */
object Routes {
    const val Splash    = "splash"
    const val Login     = "login"
    const val Register  = "register"
    const val Forgot    = "forgot"
    const val Agreement = "agreement"
    const val Privacy   = "privacy"
    const val Home      = "home"
    const val Home1     = "home1"
    const val Xiulian   = "xiulian"
    const val Shilian   = "shilian"
    const val Shilian2  = "shilian2"
    const val Shilian3  = "shilian3"
    const val Unfinished = "unfinished"
    const val PendingUnlock = "pending-unlock"
    const val Gunlun1  = "gunlun1"
    const val Gunlun2  = "gunlun2"
    const val Gunlun3  = "gunlun3"
    const val Gunlun4  = "gunlun4"
    const val Gunlun5  = "gunlun5"
    const val Gunlun6  = "gunlun6"
    const val Gunlun7  = "gunlun7"
    const val Gunlun8  = "gunlun8"
    const val Houshan  = "houshan"
    const val Learning2 = "learning2"
    const val Learning3 = "learning3"
    const val Gunlun9  = "gunlun9"
    const val Gunlun10 = "gunlun10"
    const val Gunlun11 = "gunlun11"
    const val Gunlun12 = "gunlun12"
    const val Gunlun13 = "gunlun13"
    const val Gunlun14 = "gunlun14"
    const val Gunlun15 = "gunlun15"
    const val Luggage   = "luggage"
    const val LuggageBadges = "luggage/badges"
    const val LuggageGrowth = "luggage/growth"
    const val LuggageEvidence = "luggage/evidence"
    const val LuggageManualsPattern = "luggage/manuals/{state}"
    fun luggageManuals(state: String?): String = "luggage/manuals/${state ?: "ALL"}"
    const val LuggageManualDetailPattern = "luggage/manual/{manualId}"
    fun luggageManualDetail(manualId: String): String = "luggage/manual/$manualId"
    const val LearningTrialPattern = "luggage/learning-trial/{trialId}"
    fun learningTrial(trialId: String): String = "luggage/learning-trial/$trialId"
    const val LuggageMistakes = "luggage/mistakes"
    const val LuggageMistakeDetailPattern = "luggage/mistake/{mistakeId}"
    fun luggageMistakeDetail(mistakeId: String): String = "luggage/mistake/$mistakeId"
    const val LuggageCreations = "luggage/creations"
    const val LuggageCreationDetailPattern = "luggage/creation/{projectId}"
    fun luggageCreationDetail(projectId: String): String = "luggage/creation/$projectId"
    const val LuggagePrivacySafety = "luggage/privacy_safety"
    const val RetryTrialPattern = "luggage/retry/{mistakeId}/{trialId}/{versionId}/{sessionId}"
    fun retryTrial(mistakeId: String, trialId: String, versionId: String, sessionId: String): String =
        "luggage/retry/$mistakeId/$trialId/$versionId/$sessionId"
    const val Settings  = "settings"
    const val SettingsAccount = "settings/account"
    const val SettingsMessage = "settings/message"
    const val SettingsGeneral = "settings/general"
    const val SettingsSound = "settings/sound"
    const val SettingsBlacklist = "settings/blacklist"
    const val SettingsCollection = "settings/collection"
    const val SettingsSharing = "settings/sharing"
    const val SettingsHelp = "settings/help"
    const val SettingsAbout = "settings/about"
    const val SettingsDataRecovery = "settings/data_recovery"
    const val Challenge = "challenge"
    const val Zaowu     = "zaowu"
    const val Dahui     = "dahui"
    const val Yanwuchang = "yanwuchang"
    const val YanwuchangVideo = "yanwuchang/video"
    const val YanwuchangVideoMy = "yanwuchang/video/my"
    const val YanwuchangVideoBrowseRecord = "yanwuchang/video/history"
    const val YanwuchangVideoComment = "yanwuchang/video/comments"
    const val YanwuchangVideoCommentExpanded = "yanwuchang/video/comments/expanded"
    const val DahuiArena = "dahui/arena"
    const val DahuiWorkPattern = "dahui/work/{publicationId}"
    fun dahuiWork(publicationId: String): String = "dahui/work/$publicationId"
    const val DahuiCollections = "dahui/collections"
    const val DahuiRequests = "dahui/requests"
    const val DahuiLetters = "dahui/letters"
    const val DahuiMatch = "dahui/match"
    const val DahuiMatchPattern = "dahui/match/{matchId}"
    fun dahuiMatch(matchId: String): String = "dahui/match/$matchId"
    const val Gongfang  = "gongfang"
    const val ShengtuProjectPattern = "shengtu/project/{projectId}"
    fun shengtuProject(projectId: String): String = "shengtu/project/$projectId"
    const val CreationEditorProjectPattern = "creation/editor/{projectId}"
    fun creationEditorProject(projectId: String): String = "creation/editor/$projectId"
    const val Chuangzuodangan = "chuangzuodangan"
}
